// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/service.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Fname                string   `protobuf:"bytes,2,opt,name=fname,proto3" json:"fname,omitempty"`
	City                 string   `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Phone                int64    `protobuf:"varint,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Height               float32  `protobuf:"fixed32,5,opt,name=height,proto3" json:"height,omitempty"`
	Married              bool     `protobuf:"varint,6,opt,name=married,proto3" json:"married,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_df99c249f22271d5, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetFname() string {
	if m != nil {
		return m.Fname
	}
	return ""
}

func (m *User) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *User) GetPhone() int64 {
	if m != nil {
		return m.Phone
	}
	return 0
}

func (m *User) GetHeight() float32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *User) GetMarried() bool {
	if m != nil {
		return m.Married
	}
	return false
}

type GetUsersRequest struct {
	Ids                  []int64  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersRequest) Reset()         { *m = GetUsersRequest{} }
func (m *GetUsersRequest) String() string { return proto.CompactTextString(m) }
func (*GetUsersRequest) ProtoMessage()    {}
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_df99c249f22271d5, []int{1}
}

func (m *GetUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersRequest.Unmarshal(m, b)
}
func (m *GetUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersRequest.Marshal(b, m, deterministic)
}
func (m *GetUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersRequest.Merge(m, src)
}
func (m *GetUsersRequest) XXX_Size() int {
	return xxx_messageInfo_GetUsersRequest.Size(m)
}
func (m *GetUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersRequest proto.InternalMessageInfo

func (m *GetUsersRequest) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetUsersResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersResponse) Reset()         { *m = GetUsersResponse{} }
func (m *GetUsersResponse) String() string { return proto.CompactTextString(m) }
func (*GetUsersResponse) ProtoMessage()    {}
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_df99c249f22271d5, []int{2}
}

func (m *GetUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersResponse.Unmarshal(m, b)
}
func (m *GetUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersResponse.Marshal(b, m, deterministic)
}
func (m *GetUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersResponse.Merge(m, src)
}
func (m *GetUsersResponse) XXX_Size() int {
	return xxx_messageInfo_GetUsersResponse.Size(m)
}
func (m *GetUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersResponse proto.InternalMessageInfo

func (m *GetUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "grpc.User")
	proto.RegisterType((*GetUsersRequest)(nil), "grpc.GetUsersRequest")
	proto.RegisterType((*GetUsersResponse)(nil), "grpc.GetUsersResponse")
}

func init() { proto.RegisterFile("grpc/service.proto", fileDescriptor_df99c249f22271d5) }

var fileDescriptor_df99c249f22271d5 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4e, 0xc3, 0x30,
	0x0c, 0x86, 0x49, 0xd3, 0x96, 0xe1, 0x49, 0x30, 0x59, 0x30, 0x45, 0x9c, 0xa2, 0x72, 0xc9, 0xa9,
	0x48, 0x83, 0x1b, 0x0f, 0x80, 0xc4, 0x31, 0x88, 0x07, 0x18, 0xad, 0x59, 0x73, 0x58, 0x5b, 0x92,
	0x0c, 0x89, 0x37, 0xe0, 0xb1, 0x91, 0x13, 0x26, 0xa4, 0xdd, 0xfc, 0xfd, 0xf9, 0x12, 0xc7, 0x06,
	0xdc, 0xf9, 0xb9, 0xbb, 0x0f, 0xe4, 0xbf, 0x5c, 0x47, 0xed, 0xec, 0xa7, 0x38, 0x61, 0xc9, 0x59,
	0xf3, 0x23, 0xa0, 0x7c, 0x0b, 0xe4, 0xf1, 0x12, 0x0a, 0xd7, 0x2b, 0xa1, 0x85, 0x91, 0xb6, 0x70,
	0x3d, 0x5e, 0x43, 0xf5, 0x31, 0x6e, 0xf7, 0xa4, 0x0a, 0x2d, 0xcc, 0x85, 0xcd, 0x80, 0x08, 0x65,
	0xe7, 0xe2, 0xb7, 0x92, 0x29, 0x4c, 0x35, 0x9b, 0xf3, 0x30, 0x8d, 0xa4, 0xca, 0x74, 0x39, 0x03,
	0xae, 0xa1, 0x1e, 0xc8, 0xed, 0x86, 0xa8, 0x2a, 0x2d, 0x4c, 0x61, 0xff, 0x08, 0x15, 0x9c, 0xef,
	0xb7, 0xde, 0x3b, 0xea, 0x55, 0xad, 0x85, 0x59, 0xd8, 0x23, 0x36, 0x77, 0x70, 0xf5, 0x4c, 0x91,
	0x3f, 0x13, 0x2c, 0x7d, 0x1e, 0x28, 0x44, 0x5c, 0x81, 0x74, 0x7d, 0x50, 0x42, 0x4b, 0x23, 0x2d,
	0x97, 0xcd, 0x23, 0xac, 0xfe, 0xa5, 0x30, 0x4f, 0x63, 0x20, 0xd4, 0x50, 0x1d, 0x38, 0x48, 0xde,
	0x72, 0x03, 0x2d, 0x4f, 0xd6, 0xb2, 0x63, 0xf3, 0xc1, 0xe6, 0x05, 0x96, 0x8c, 0xaf, 0x79, 0x01,
	0xf8, 0x04, 0x8b, 0xe3, 0x23, 0x78, 0x93, 0xed, 0x93, 0xce, 0xb7, 0xeb, 0xd3, 0x38, 0xf7, 0x6a,
	0xce, 0xde, 0xeb, 0xb4, 0xbe, 0x87, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x63, 0xe9, 0xe1, 0xff,
	0x54, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error) {
	out := new(GetUsersResponse)
	err := c.cc.Invoke(ctx, "/grpc.UserService/GetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	GetUsers(context.Context, *GetUsersRequest) (*GetUsersResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) GetUsers(ctx context.Context, req *GetUsersRequest) (*GetUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.UserService/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUsers(ctx, req.(*GetUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsers",
			Handler:    _UserService_GetUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/service.proto",
}
